### PR TITLE
Croatian translations

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by EduardDopler** [comment]
Thank you for your contribution.
Just a few things:

Please …
- add yourself as `Last-Translator`,
- don't remove the `#, python-format` from the _nemo-compare_ translation,
- update the header of the _nemo-terminal_ translation,
- replace the `VERSION` from the _nemo-metadata-columns_ translation with the current version,
- remove the double appearance of `Last-Translator` from _nemo-metadata-columns_ and _nemo-metadata-tab_.

**Comment by muzena** [comment]
@EduardDopler 
Is this normal in nemo-metadata-colums, in Length colummn  letter h is shown, see in screenshot:
screenshot from 2016-01-21 21 54 15

In second screenshot nemo-preview 'items' string is not translatable.
screenshot from 2016-01-21 21 55 02

**Comment by EduardDopler** [comment]
Yes, prepending the letter _h_ is [wanted behavior](https://github.com/EduardDopler/nemo-extensions/blob/master/nemo-metadata-columns/src/nemo-metadata-columns.py#L580) as it indicates that this information shows hours instead of minutes. Another solution would be to always show the format _HH:MM:SS_ but then you see a lot of space-consuming "00:" prepended in files with durations smaller than one hour.

You are right with `nemo-preview` and the untranslated string. Actually, nothing is translated from inside that extension; everything locale comes directly from Gtk, if I see it right. So one would have to implement localization from the ground up for that javascript based extension. I'll postpone that for now.

**Comment by muzena** [comment]
@EduardDopler Update headers of po files

**Comment by EduardDopler** [comment]
Nice work :thumbsup:

**Comment by muzena** [comment]
@EduardDopler I think that is format HH:MM:SS better solution. Character h in my language and I think on many others looks confusing and strange like some bug.  space-consuming "00:" I think that is insignificant it's only two spaces.

**Comment by EduardDopler** [comment]
Another reason is that the tool I'm using for the time information of media files doesn't return seconds if the duration is ≥1h, i.e. the format is always xx:yy. So if hours are involved I cannot retrieve the seconds.

**Pull request merged**
